services:
  app:
    image: ghcr.io/ducheved/gomymoney:latest
    environment:
      - BOT_TOKEN=${API_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - app-data:/app/data
    depends_on:
      - watchtower
    networks:
      - gomymoney-network
    labels:
      - com.centurylinklabs.watchtower.enable=true
volumes:
  app-data:
networks:
  gomymoney-network:
    driver: bridge